image: docker:git

stages:
  - deploy

before_script:
  - apk --update add bash ruby ruby-dev

services:
  - docker:stable-dind

release:
  stage: deploy
  when: manual
  script:
    - mkdir -p ~/.gem/credentials
    - "echo ':rubygems_api_key: $GEM_TOKEN' > ~/.gem/credentials"
    - gem build cassette-rails.gemspec
    - gem push $(find . -name *.gem)

