trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cassette

steps:
  - bash: |
      set -e
      sudo apt-get install ruby-full rubygems
      mkdir -p ~/.gem
      echo ":rubygems_api_key: $env:GEM_TOKEN" > ~/.gem/credentials
      chmod 0600 ~/.gem/credentials
      gem build cassette-rails.gemspec
      gem push $(find . -name *.gem)
    displayName: "Publish gem"
    env:
      GEM_TOKEN: $(GEM_TOKEN)
